services:
  - type: web
    name: media-recomm-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: "!/assets/*"
        destination: /index.html
      - type: rewrite
        source: "!/static/*"
        destination: /index.html